SELECT SYSDATE FROM DUAL;

-- ADD_MONTHS(d,i)
SELECT SYSDATE , ADD_MONTHS(SYSDATE, -1) AS "anterior",
    ADD_MONTHS(SYSDATE, 12) AS "siguiente"
FROM DUAL;

-- ALTER SESSION SET nls_date_format = 'DD/MM/RR HH24:MI:SS';

SELECT  MONTHS_BETWEEN('31/03/08', '30/09/08') f1,
        ROUND(MONTHS_BETWEEN('11/03/08', '30/09/08'), 1) f2,
        ROUND(MONTHS_BETWEEN('01/03/08', '30/09/08'), 1) f3,
        MONTHS_BETWEEN('31/03/08', '30/09/07') f4
FROM DUAL;

SELECT SYSDATE,
    LAST_DAY(SYSDATE) AS "fin_de_mes",
    LAST_DAY(SYSDATE) + 1 AS "siguiente"
FROM DUAL;

-- ROUND(d [,fmt])
SELECT SYSDATE, ROUND(SYSDATE, 'HH24') AS "ROUND_HOUR",
    ROUND(SYSDATE) AS "ROUND_DATE", ROUND(SYSDATE, 'MM') AS "NEW_MONTH",
    ROUND(SYSDATE, 'YY') AS "NEW_YEAR"
FROM DUAL;

-- TRUNC(d [,fmt])
SELECT SYSDATE, TRUNC(SYSDATE, 'HH24') AS "TRUNC_HOUR",
    TRUNC(SYSDATE) AS "TRUNC_DATE", TRUNC(SYSDATE, 'MM') AS "NEW_MONTH",
    TRUNC(SYSDATE, 'YY') AS "NEW_YEAR"
FROM DUAL;



