-- TO_DATE(c[, fmt[, nslparam]])

ALTER SESSION SET nls_date_format = 'DD-MON-RR HH24:MI:SS';

SELECT TO_DATE('25-DEC-2010') FROM DUAL;

SELECT TO_DATE('25-DEC', 'DD-MON') FROM DUAL;

SELECT TO_DATE('25-DEC-2010 18:03:45', 'DD-MON-YYYY HH24:MI:SS')
FROM DUAL;

SELECT TO_DATE('30-SEP-2007', 'DD/MON/YY') FROM DUAL;

SELECT TO_DATE('SEP-2007 13', 'MON/YYYY HH24') FROM DUAL;

SELECT first_name, last_name, hire_date
FROM employees
WHERE hire_date > TO_DATE('01/12/2000', 'MM/DD/YYYY')
ORDER BY hire_date;

